<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="../DirectorAdmission.cs" Link="DirectorAdmission.cs" />
    <Compile Include="../IntelligenceChannel.cs" Link="IntelligenceChannel.cs" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
