import { isUuid } from '../identity/identityContract.mjs';

const exact = (v, required, optional = []) => !!v && typeof v==='object' && !Array.isArray(v) && required.every(k=>Object.hasOwn(v,k)) && Object.keys(v).every(k=>required.includes(k)||optional.includes(k));
const integer = (n, max = Number.MAX_SAFE_INTEGER) => Number.isSafeInteger(n) && n >= 0 && n <= max;
const tick = n => integer(n, 0xffffffff);
const enumIs = (v, values) => values.includes(v);

export function validateCaptureReceipt(r) {
  if (!exact(r, ['speechVersion','nativeRun','producerId','producerSequence','utteranceId','captureReceiptRef','source','startGameTick','endGameTick','startMonotonicMs','endMonotonicMs','durationMs','observers'],['conversationRef']) || r.speechVersion !== 1 || !isUuid(r.nativeRun) || r.producerId!=='player_mic' || !integer(r.producerSequence) || r.producerSequence===0 || !isUuid(r.utteranceId) || !isUuid(r.captureReceiptRef) || r.conversationRef!==undefined&&!isUuid(r.conversationRef) || !exact(r.source,['captureRef','kind']) || !isUuid(r.source.captureRef) || r.source.kind !== 'player' || !tick(r.startGameTick) || !tick(r.endGameTick) || !integer(r.startMonotonicMs) || !integer(r.endMonotonicMs) || r.endMonotonicMs < r.startMonotonicMs || !integer(r.durationMs,30000) || r.durationMs < 1 || !Array.isArray(r.observers) || r.observers.length > 16) return false;
  const duration = r.endMonotonicMs - r.startMonotonicMs;
  if (Math.abs(duration - r.durationMs) > 1000) return false;
  return new Set(r.observers.map(o=>o?.observer?.captureRef)).size===r.observers.length && r.observers.every(o => exact(o,['observer','sampledGameTick','distanceMeters','acousticPath','audibleIntervalsMs','hearing','reasonCodes','acousticContext']) && exact(o.observer,['captureRef','kind']) && isUuid(o.observer.captureRef) && o.observer.kind === 'ped' && tick(o.sampledGameTick) && tickBetween(o.sampledGameTick,r.startGameTick,r.endGameTick) && Number.isFinite(o.distanceMeters)&&o.distanceMeters>=0&&o.distanceMeters<=1000 && enumIs(o.acousticPath,['clear','blocked','unknown']) && Array.isArray(o.audibleIntervalsMs) && o.audibleIntervalsMs.length <= 4 && o.audibleIntervalsMs.every(i=>exact(i,['start','end'])&&integer(i.start,30000)&&integer(i.end,30000)&&i.end>i.start&&i.end<=r.durationMs) && enumIs(o.hearing,['heard','did_not_hear','unknown']) && Array.isArray(o.reasonCodes)&&o.reasonCodes.length<=4&&o.reasonCodes.every(c=>typeof c==='string'&&/^[a-z][a-z0-9_]{0,47}$/.test(c)) && exact(o.acousticContext,['occlusion','interior','sourceVehicle','observerVehicle','sourceFacingToObserver','attention']) && enumIs(o.acousticContext.occlusion,['clear','blocked','unknown']) && enumIs(o.acousticContext.interior,['same','different','unknown']) && enumIs(o.acousticContext.sourceVehicle,['on_foot','enclosed','open','unknown']) && enumIs(o.acousticContext.observerVehicle,['on_foot','enclosed','open','unknown']) && enumIs(o.acousticContext.sourceFacingToObserver,['in_cone','outside_cone','unknown']) && enumIs(o.acousticContext.attention,['attending','distracted','unknown']) && (o.hearing!=='heard'||o.audibleIntervalsMs.length>0&&o.acousticPath==='clear'&&o.acousticContext.interior==='same'&&o.acousticContext.occlusion==='clear'&&o.acousticContext.sourceVehicle!=='unknown'&&o.acousticContext.observerVehicle!=='unknown'&&o.distanceMeters<=(o.acousticContext.sourceVehicle==='enclosed'||o.acousticContext.observerVehicle==='enclosed'?6:12)) && (o.hearing!=='did_not_hear'||o.audibleIntervalsMs.length===0&&o.reasonCodes.some(c=>['out_of_range','different_interior','acoustic_path_blocked','vehicle_policy_reject'].includes(c))) && (o.hearing!=='unknown'||o.audibleIntervalsMs.length===0));
}

export function validateAcceptedTranscript(t, { activeNativeRun = null, now = 0 } = {}) {
  if (!exact(t,['nativeRun','utteranceId','transcriptRef','revision','origin','text','acceptedAtMonotonicMs','expiresAtMonotonicMs']) || !isUuid(t.nativeRun) || !isUuid(t.utteranceId) || !isUuid(t.transcriptRef) || t.revision !== 1 || t.origin !== 'player_stt' || typeof t.text !== 'string' || !t.text.trim() || Buffer.byteLength(t.text,'utf8')>4096 || /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(t.text) || !integer(t.acceptedAtMonotonicMs) || !integer(t.expiresAtMonotonicMs) || t.expiresAtMonotonicMs<=t.acceptedAtMonotonicMs || t.expiresAtMonotonicMs>t.acceptedAtMonotonicMs+30000 || t.acceptedAtMonotonicMs>now || activeNativeRun && t.nativeRun!==activeNativeRun) return false;
  return true;
}

function tickBetween(value,start,end) { return ((value-start)>>>0)<=((end-start)>>>0); }
