<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net481</TargetFramework><LangVersion>latest</LangVersion><AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages></PropertyGroup><ItemGroup><Compile Include="../ClrDomains.cs" Link="ClrDomains.cs"/><Compile Include="../DomainHost.cs" Link="DomainHost.cs"/></ItemGroup></Project>
