<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework><AssemblyName>LSA.PromotedCharacters</AssemblyName><LangVersion>latest</LangVersion>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages><Deterministic>true</Deterministic><GenerateAssemblyInfo>false</GenerateAssemblyInfo><EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="EntryPoint.cs;PlayerCommands.cs;ClrDomains.cs;DomainHost.cs" />
    <ProjectReference Include="PromotedCharacters.csproj" ReferenceOutputAssembly="false" />
    <Reference Include="RagePluginHook"><HintPath>$(RphReferencePath)</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
